name: Workflow Main

on: [ pull_request, push ]

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  test:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.0.0

  android_build:
    environment: Staging
    if: ${{ always() && (needs.semantic-pull-request.result=='success' || needs.test.result=='success') }}
    needs: ['semantic-pull-request', 'test']
    uses: ./.github/workflows/build-android.yaml
    secrets: inherit
    with:
      flutter_channel: stable
      flutter_version: 3.0.0
