name: Workflow Main

on: [ pull_request, push ]

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.0.0

  workflow_dispatch:    
    uses: deadmantfa/workflow_test/.github/workflows/build-android.yml@v1.2
    with:
        token: ${{ secrets.PERSONAL_TOKEN }}
        inputs: '{ "flutter_channel": "stable", "flutter_version": "3.0.0" }'
